"""B-001 closure (Enterprise Security Review 2026-06-18) — chain_sequence column

Revision ID: z1a2b3c4d5e6
Revises: y0a1b2c3d4e5
Create Date: 2026-06-18 22:45:00.000000

Adds `chain_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY` to audit_logs.

Why: external auditors walking the hash chain via `ORDER BY created_at ASC`
hit a false-positive break rate of ~9% per shard because two concurrent
INSERTs can land sub-microsecond apart, and Postgres tie-breaks differently
than the insertion sequence the chain was built in. `chain_sequence` is
assigned by the DB at INSERT time and is monotonically increasing per shard,
so the canonical chain walk is:

    SELECT event_hash, prev_hash
    FROM audit_logs
    WHERE tenant_id = $1 AND chain_shard = $2
    ORDER BY chain_sequence ASC;

NULL on rows inserted before the migration (legacy); the verifier should
treat NULL as "fall back to created_at + id". New writes always get a value.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "z1a2b3c4d5e6"
down_revision: str | None = "y0a1b2c3d4e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # IDENTITY columns are implicitly NOT NULL in PostgreSQL; the prior
    # ``nullable=True`` produced "conflicting NULL/NOT NULL declarations".
    # Adding as IDENTITY backfills existing rows with sequential values
    # from the sequence, so the canonical chain walk is well-defined for
    # rows that pre-existed the migration too.
    op.add_column(
        "audit_logs",
        sa.Column(
            "chain_sequence",
            sa.BigInteger(),
            sa.Identity(always=False, start=1, cycle=False),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_audit_logs_chain_sequence",
        "audit_logs",
        ["tenant_id", "chain_shard", "chain_sequence"],
    )


def downgrade() -> None:
    op.drop_index("ix_audit_logs_chain_sequence", table_name="audit_logs")
    op.drop_column("audit_logs", "chain_sequence")
