#!/usr/bin/env bash
# Backup every operator-supplied secret + parameter value BEFORE the
# destroy run. Anything generated by Terraform (random_password) is
# regenerated on apply and does NOT need backup; this script captures
# only the values you set manually that Terraform cannot reproduce.
#
# OUTPUT:
#   /tmp/aegis-backup-<ts>/<category>/<name>.value   plain text per value
#   /tmp/aegis-backup-<ts>/MANIFEST.json             machine-readable index
#   /tmp/aegis-backup-<ts>.tar.gz.age                age-encrypted archive
#
# AFTER RUNNING:
#   1. Verify the archive opens with your age key on a second machine.
#   2. Copy the .age archive to offline / cold storage.
#   3. Only then run destroy_old_cloud.sh.

set -euo pipefail

: "${AWS_REGION:=ap-south-1}"
: "${BACKUP_AGE_RECIPIENT:?Set BACKUP_AGE_RECIPIENT to your age public key (age1...). Get it from: age-keygen -o ~/.config/age/key.txt}"

TS="$(date -u +%Y%m%d-%H%M%S)"
ROOT="/tmp/aegis-backup-${TS}"
mkdir -p "${ROOT}/secrets" "${ROOT}/params"

log() { printf '[%s] %s\n' "$(date -u +%H:%M:%S)" "$*"; }

# ─── Secrets Manager ───────────────────────────────────────────────────
log "Backing up Secrets Manager values from acp-prodha/* ..."
for name in \
  "acp-prodha/stripe_webhook_secret" \
  "acp-prodha/rds_master_password" \
  "acp-prodha/internal_secret" \
  "acp-prodha/jwt_secret_key" \
  "acp-prodha/redis_auth_token" \
  "acp-prodha/mesh_jwt_secret" \
  "acp-prodha/groq_api_key" \
; do
  safe="${name//\//__}"
  if aws --region "${AWS_REGION}" secretsmanager describe-secret --secret-id "${name}" >/dev/null 2>&1; then
    aws --region "${AWS_REGION}" secretsmanager get-secret-value \
        --secret-id "${name}" \
        --query 'SecretString' --output text > "${ROOT}/secrets/${safe}.value"
    log "  ✓ ${name}"
  else
    log "  - ${name} (not found, skipping)"
  fi
done

# ─── SSM Parameters — /aegis-prodha/* + /acp-prodha/* ───────────────────
log "Backing up SSM Parameter values ..."
PARAM_NAMES=$(aws --region "${AWS_REGION}" ssm describe-parameters \
  --parameter-filters 'Key=Name,Option=BeginsWith,Values=/aegis-prodha/,/acp-prodha/' \
  --query 'Parameters[].Name' --output text 2>/dev/null || true)

if [[ -z "${PARAM_NAMES}" ]]; then
  log "  (no parameters matched /aegis-prodha/ or /acp-prodha/ — odd, check region)"
else
  for name in ${PARAM_NAMES}; do
    safe="${name//\//__}"
    val="$(aws --region "${AWS_REGION}" ssm get-parameter \
              --name "${name}" --with-decryption \
              --query 'Parameter.Value' --output text 2>/dev/null || echo "")"
    if [[ -n "${val}" ]]; then
      printf '%s' "${val}" > "${ROOT}/params/${safe}.value"
      log "  ✓ ${name}"
    else
      log "  ! ${name} (empty or unreadable)"
    fi
  done
fi

# ─── KMS keys — note metadata; key material itself is not exportable ───
log "Recording KMS key metadata (alias/aegis-audit-envelope) ..."
aws --region "${AWS_REGION}" kms describe-key \
    --key-id alias/aegis-audit-envelope \
    --query 'KeyMetadata.[KeyId,Arn,CreationDate,KeyManager,Description]' \
    --output json > "${ROOT}/kms-audit-envelope.json" || \
    log "  alias/aegis-audit-envelope not found, skipping"

# ─── RDS — take a final manual snapshot ────────────────────────────────
log "Taking a final RDS snapshot (manual, never expires until you delete it) ..."
aws --region "${AWS_REGION}" rds create-db-snapshot \
    --db-snapshot-identifier "aegis-final-pre-destroy-${TS}" \
    --db-instance-identifier "acp-prodha-postgres" \
    --query 'DBSnapshot.[DBSnapshotIdentifier,Status]' --output text \
    | tee "${ROOT}/rds-snapshot.txt"

# ─── Public roots bucket — backup the entire bucket (cheap, lifecycle bypass) ──
log "Mirroring s3://aegis-public-roots-628478946931 to internal backup ..."
aws --region "${AWS_REGION}" s3 sync \
    s3://aegis-public-roots-628478946931/ \
    s3://acp-backups-prodha-628478946931/public-roots-pre-rebuild-${TS}/ \
    --no-progress > "${ROOT}/public-roots-mirror.log" 2>&1 || \
    log "  mirror failed, see ${ROOT}/public-roots-mirror.log"

# ─── Manifest ──────────────────────────────────────────────────────────
log "Writing manifest ..."
cat > "${ROOT}/MANIFEST.json" <<EOF
{
  "version": "1",
  "captured_at": "${TS}",
  "region": "${AWS_REGION}",
  "account_id": "$(aws sts get-caller-identity --query Account --output text)",
  "rds_snapshot": "aegis-final-pre-destroy-${TS}",
  "public_roots_mirror": "s3://acp-backups-prodha-628478946931/public-roots-pre-rebuild-${TS}/",
  "secrets_files":   $(ls "${ROOT}/secrets" 2>/dev/null | jq -R . | jq -s .),
  "params_files":    $(ls "${ROOT}/params"  2>/dev/null | jq -R . | jq -s .),
  "destroy_safety": "ONLY DESTROY AFTER VERIFYING THIS BACKUP DECRYPTS ON A SECOND MACHINE."
}
EOF

# ─── Encrypt the archive ───────────────────────────────────────────────
log "Encrypting archive to ${ROOT}.tar.gz.age ..."
tar -czf - -C "$(dirname "${ROOT}")" "$(basename "${ROOT}")" \
  | age -r "${BACKUP_AGE_RECIPIENT}" -o "${ROOT}.tar.gz.age"
log "Archive size: $(stat -f '%z' "${ROOT}.tar.gz.age") bytes"

# ─── Drop the plain-text staging ───────────────────────────────────────
log "Wiping plain-text staging at ${ROOT}/ ..."
find "${ROOT}" -type f -exec sh -c 'dd if=/dev/urandom of="$1" bs=1k count=1 2>/dev/null; rm -f "$1"' _ {} \;
rmdir -p "${ROOT}/secrets" "${ROOT}/params" 2>/dev/null || true
rmdir "${ROOT}" 2>/dev/null || true

echo
echo "============================================================"
echo "  Backup complete."
echo "  Encrypted archive: ${ROOT}.tar.gz.age"
echo
echo "  VERIFY before destroy:"
echo "    age -d -i ~/.config/age/key.txt ${ROOT}.tar.gz.age > /tmp/test.tar.gz"
echo "    tar -tzf /tmp/test.tar.gz | head"
echo
echo "  THEN run scripts/destroy_old_cloud.sh."
echo "============================================================"
